### ISSUE TITLE
Publish deprecation message to NPM

### ISSUE THREAD

**Issue by michaellopez** [joliss/broccoli-static-compiler#17]
The [npm page](https://www.npmjs.com/package/broccoli-static-compiler) does not state anything about deprecation in favor of [broccoli-funnel](https://github.com/rwjblue/broccoli-funnel). I think it should, so that users who are looking for this functionality but who do not read the github page or readme get the latest and greatest.

**Comment by joliss** [comment]
Fixed, thanks!
